openapi: 3.0.1
info:
  title: Prices Management
  description: API for managing prices.
  version: 1.0.0
servers:
  - url: "http://localhost:{port}/{version}/api"
    variables:
      port:
        default: '8082'
      version:
        default: '1'
paths:
  /prices:
    get:
      tags:
        - Prices
      summary: Get Prices
      operationId: getPrices
      parameters:
        - name: productId
          in: query
          schema:
            type: integer
            format: int64
            example: 1
            description: The product ID number.
        - name: brandId
          in: query
          schema:
            type: integer
            format: int64
            example: 1
            description: The brand ID number.
        - in: query
          name: filterDate
          schema:
            type: string
            format: date-time
            description: Filter date and time.
            example: "2021-01-30T08:30:00Z"
      responses:
        200:
          description: A prices item.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PricesResponseDto'

components:
  schemas:
    PricesResponseDto:
      type: object
      properties:
        brandId:
          type: integer
          format: int64
          description: The brand ID.
        productId:
          type: integer
          format: int64
          description: The product ID.
        priceList:
          type: integer
          format: int64
          description: The price list value.
        price:
          type: number
          format: double
          description: The price value.
        startDate:
          type: string
          format: date-time
          description: The start date value.
        endDate:
          type: string
          format: date-time
          description: The end date value.